// Generated by scripts/generate-env.mjs. Do not edit manually.
export const environment = {
  apiUrl: "http://localhost:3333/api",
  firebase: {
  "apiKey": "AIzaSyDQeqtlEMvm1Qj0KLhd5IzB-ha0sSEPUlM",
  "authDomain": "caverna-digital-3c941.firebaseapp.com",
  "projectId": "caverna-digital-3c941",
  "storageBucket": "caverna-digital-3c941.firebasestorage.app",
  "messagingSenderId": "520800711906",
  "appId": "1:520800711906:web:cf5c10501819b92e2c5abb"
},
};
