import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const envPath = resolve('.env');
const outputPath = resolve('src/environments/environment.ts');
const fallbackApiUrl = 'http://localhost:3333/api';

function parseEnv(content) {
  return content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .reduce((env, line) => {
      const separatorIndex = line.indexOf('=');
      if (separatorIndex === -1) return env;

      const key = line.slice(0, separatorIndex).trim();
      const value = line.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');
      return { ...env, [key]: value };
    }, {});
}

let env = {};

try {
  env = parseEnv(readFileSync(envPath, 'utf8'));
} catch {
  env = {};
}

const apiUrl =
  process.env.MASTER_ADMIN_API_URL ||
  process.env.API_URL ||
  env.MASTER_ADMIN_API_URL ||
  env.API_URL ||
  fallbackApiUrl;

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || env.FIREBASE_API_KEY || 'AIzaSyDQeqtlEMvm1Qj0KLhd5IzB-ha0sSEPUlM',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || env.FIREBASE_AUTH_DOMAIN || 'caverna-digital-3c941.firebaseapp.com',
  projectId: process.env.FIREBASE_PROJECT_ID || env.FIREBASE_PROJECT_ID || 'caverna-digital-3c941',
  storageBucket:
    process.env.FIREBASE_STORAGE_BUCKET || env.FIREBASE_STORAGE_BUCKET || 'caverna-digital-3c941.firebasestorage.app',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || env.FIREBASE_MESSAGING_SENDER_ID || '520800711906',
  appId: process.env.FIREBASE_APP_ID || env.FIREBASE_APP_ID || '1:520800711906:web:cf5c10501819b92e2c5abb',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || env.FIREBASE_MEASUREMENT_ID || 'G-WM1CJPWHRP',
};

const environmentFile = `// Generated by scripts/generate-env.mjs. Do not edit manually.
export const environment = {
  apiUrl: ${JSON.stringify(apiUrl)},
  firebase: ${JSON.stringify(firebaseConfig, null, 2)},
};
`;

writeFileSync(outputPath, environmentFile);
console.log(`Environment generated with MASTER_ADMIN_API_URL=${apiUrl}`);
