import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const envPath = resolve('.env');
const outputPath = resolve('src/environments/environment.ts');
const fallbackApiUrl = 'http://localhost:3333/api';

function parseEnv(content) {
  return content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .reduce((env, line) => {
      const separatorIndex = line.indexOf('=');
      if (separatorIndex === -1) return env;

      const key = line.slice(0, separatorIndex).trim();
      const value = line.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');
      return { ...env, [key]: value };
    }, {});
}

let env = {};

try {
  env = parseEnv(readFileSync(envPath, 'utf8'));
} catch {
  env = {};
}

const apiUrl =
  process.env.MASTER_ADMIN_API_URL ||
  process.env.API_URL ||
  env.MASTER_ADMIN_API_URL ||
  env.API_URL ||
  fallbackApiUrl;

const environmentFile = `// Generated by scripts/generate-env.mjs. Do not edit manually.
export const environment = {
  apiUrl: ${JSON.stringify(apiUrl)},
};
`;

writeFileSync(outputPath, environmentFile);
console.log(`Environment generated with MASTER_ADMIN_API_URL=${apiUrl}`);
